/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

    THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
    KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
    PURPOSE.

Module Name:

    public.h

Abstract:

Environment:

    User & Kernel mode

--*/

#pragma once

#include <initguid.h>

// {4262d7ac-b4d6-40d5-af6d-355ee714ef0b}
DEFINE_GUID(
  GUID_CLASS_RIO500_USB, 
  0x4262d7ac, 0xb4d6, 0x40d5, 0xaf, 0x6d, 0x35, 0x5e, 0xe7, 0x14, 0xef, 0x0b
);

#define IOCTL_INDEX 0x0000

#define IOCTL_RIO500_GET_CONFIG_DESCRIPTOR \
  CTL_CODE(FILE_DEVICE_UNKNOWN, IOCTL_INDEX + 0, METHOD_BUFFERED, FILE_ANY_ACCESS)
                                                   
#define IOCTL_RIO500_RESET_DEVICE \
  CTL_CODE(FILE_DEVICE_UNKNOWN, IOCTL_INDEX + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_RIO500_RESET_PIPE \
  CTL_CODE(FILE_DEVICE_UNKNOWN, IOCTL_INDEX + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_RIO500_RIO_COMMAND \
  CTL_CODE(FILE_DEVICE_UNKNOWN, IOCTL_INDEX + 3, METHOD_BUFFERED, FILE_ANY_ACCESS)
