#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDS_ICON_OFF                            144
#define IDS_ICON_ON                             145
#define IDD_DIALOG_FORMATTING                   147
#define IDS_EXPLORE                             40000
#define IDS_OPEN                                40001
#define IDS_GROUPBYSIDES                        40002
#define IDS_EXPLORE_HELP                        40003
#define IDS_OPEN_HELP                           40004
#define IDS_ONE                                 40005
#define IDS_TWO                                 40006
#define IDS_THREE                               40007
#define IDS_FOUR                                40008
#define IDS_FIVE                                40009
#define IDS_SIX                                 40010
#define IDS_SEVEN                               40011
#define IDS_EIGHT                               40012
#define IDS_NINE                                40013
#define IDS_ZERO                                40014
#define IDS_GROUPBYSIZE                         40015
#define IDS_GROUPBYALPHA                        40016
#define IDS_VALUE                               40017
#define IDS_SMALL                               40018
#define IDS_MEDIUM                              40019
#define IDS_LARGE                               40020
#define IDS_LESSTHAN5                           40021
#define IDS_5ORGREATER                          40022
#define IDS_GROUPBYVALUE                        40023
#define IDS_GROUPBYLEVEL                        40024
#define IDS_RECTANGLE                           40025
#define IDS_TRIANGLE                            40026
#define IDS_CIRCLE                              40027
#define IDS_POLYGON                             40028
#define IDS_TITLE                               40029
#define IDS_DISPLAY                             40030
#define IDS_FORMAT                              40031
#define IDS_UNSPECIFIED                         40032
#define IDS_SETTINGS                            40033
#define IDS_SETTING1                            40034
#define IDS_SETTING2                            40035
#define IDS_SETTING3                            40036
#define IDS_DISPLAY_TT                          40037
#define IDS_SETTINGS_TT                         40038
#define IDS_SETTING1_TT                         40039
#define IDS_SETTING2_TT                         40040
#define IDS_SETTING3_TT                         40041
